# 基础镜像  leaf
FROM  openjdk:8-jre
# author
MAINTAINER xiaowenhao
# 挂载目录
VOLUME /home/changji
# 创建目录
RUN mkdir -p /home/changji
# 指定路径
WORKDIR /home/changji
# 复制jar文件到路径
COPY ./jar/cjxycloud-leaf.jar /home/changji/cjxycloud-leaf.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","cjxycloud-leaf.jar"]
